services:
  db:
    image: postgres:16
    container_name: carehub-postgres
    environment:
      POSTGRES_DB: carehub
      POSTGRES_USER: carehub
      POSTGRES_PASSWORD: carehub_pw
    ports:
      - "5432:5432"
    volumes:
      - carehub_pgdata:/var/lib/postgresql/data

volumes:
  carehub_pgdata: